### ISSUE TITLE
Ability to add custom context

### ISSUE THREAD

**Issue by pgorod** [Nerwyn/ha-nunjucks#1]
Currently, only some HASS context is available to the template. But it would be useful to be able to add more arbitrary context, including full objects, to be made available inside the template.

Something like this:
```
ha-nunjucks.addContext({ username: 'James' });
ha-nunjucks.addContext({ goes: 'here' });
ha-nunjucks.addContext({ tasklist: someObject });
ha-nunjucks.render('the template text goes {{ goes }}, using any parts of the context it wants');
```

For reference, here's the [forum thread that started this suggestion](https://community.home-assistant.io/t/how-to-invoke-jinja-processing-in-my-card-js-code/636172/14?u=pgr).

Thanks!

**Comment by Nerwyn** [comment]
Added in [v1.2.0](https://github.com/Nerwyn/ha-nunjucks/releases/tag/1.2.0)

```typescript
import { renderTemplate } from 'ha-nunjucks';

const context = {
  foo: 'bar',
  doThing(thing: string) {
    return `doing ${thing}!`;
  },
};

const renderedString = renderTemplate(this.hass, templateString, context);
```

**Comment by Nerwyn** [comment]
The same way you'd use Home Assistant templating functions like `is_state`:

```typescript
import { renderTemplate } from 'ha-nunjucks';

const context = {
  foo: 'bar',
  doThing(thing: string) {
    return `doing ${thing}!`;
  },
};

const templateString = '{{ doThing("my taxes") }}';
const renderedString = renderTemplate(this.hass, templateString, context);
console.log(renderedString);

> doing my taxes!
```

It's up to developers to decide what to do with it. It is extending the templating syntax.

**Comment by pgorod** [comment]
Thanks for the explanation, I will explore this.
